# Generated by Django 3.2 on 2022-11-15 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmwork',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='filmwork',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='person',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='person',
            name='updated_at',
        ),
    ]
