# Generated by Django 3.2 on 2022-11-15 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20221116_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genrefilmwork',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='personfilmwork',
            name='created_at',
        ),
    ]
