# Generated by Django 3.2 on 2022-12-04 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20221204_1356'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='personfilmwork',
            name='film_work_person_role_idx',
        ),
        migrations.RemoveField(
            model_name='personfilmwork',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='personfilmwork',
            name='role',
        ),
    ]
