# Generated by Django 3.2 on 2022-12-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20221204_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='personfilmwork',
            name='role',
            field=models.CharField(choices=[('actor', 'Actor'), ('screenwriter', 'Screenwriter'), ('producer', 'Producer'), ('editor', 'Editor'), ('director', 'Director')], default='actor', max_length=100, verbose_name='role'),
        ),
        migrations.AddIndex(
            model_name='personfilmwork',
            index=models.Index(fields=['film_work', 'person', 'role'], name='film_work_person_role_idx'),
        ),
    ]
