# Generated by Django 3.2 on 2022-11-15 21:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20221116_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='genrefilmwork',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 15, 21, 58, 34, 626984, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personfilmwork',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 15, 21, 58, 39, 870233, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
