# Generated by Django 3.2 on 2022-12-04 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20221204_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='personfilmwork',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created_at'),
            preserve_default=False,
        ),
    ]
