# Generated by Django 3.2 on 2022-11-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20221116_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='personfilmwork',
            name='role',
            field=models.TextField(null=True, verbose_name='role'),
        ),
    ]
