# Generated by Django 3.2 on 2022-11-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_personfilmwork_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='creation_date',
            field=models.DateField(blank=True, verbose_name='creation date'),
        ),
    ]
