# Указываем образ, от которого берётся наследование
FROM ubuntu:18.04

# Обновляем индекс пакетов
RUN apt update -y

RUN cat /etc/os-release | grep PRETTY_NAME
# Устанавливаем интерпретатор
RUN apt install -y python3

# Указываем команду, которая должна выполниться при старте контейнера
CMD ["python3"]